### ISSUE TITLE
Bug: /meet route not working correctly. [rpc error]

### ISSUE THREAD

**Issue by lennykr** [aCubed-tm/authentication-service#28]
~~Ik krijg die API niet werkende~~ Andere routes werken wel: Dus fout gevonden in volgende route. Ik maak een issue aan. 

**Request**  `POST http://10.103.153.221/v1/auth/meet` :
```json
{
    "email": "email@acubed.app"
}
```

**Response:**
```json
{
    "error": {
        "message": "rpc error: code = Unavailable desc = transport is closing"
    }
}
```

**Log:**
```bash
[edge-59db768546-c6rr7 edge] 2020/02/15 11:28:23 Starting gRPC connection to authentication-service.acubed:50551
[edge-59db768546-c6rr7 edge] 2020/02/15 11:28:25 Returning error: rpc error: code = Unavailable desc = transport is closing
[edge-59db768546-c6rr7 edge] 2020/02/15 11:28:25 "POST http://10.103.153.221/v1/auth/meet HTTP/1.1" from 192.168.64.1:55143 - 200 98B in 2.078467396s
```

**Comment by lennykr** [comment]
Full log:
```bash
[edge-59db768546-c6rr7 edge] 2020/02/15 12:55:21 Starting gRPC connection to authentication-service.acubed:50551
[authentication-service-84cfcf8786-jl55l authentication-service] panic: interface conversion: interface {} is nil, not string
[authentication-service-84cfcf8786-jl55l authentication-service]
[authentication-service-84cfcf8786-jl55l authentication-service] goroutine 15 [running]:
[authentication-service-84cfcf8786-jl55l authentication-service] main.GetUuidByEmail(0xc000028880, 0x17, 0xc0000f9ac0, 0x40fab3, 0x908b00, 0x920d60)
[authentication-service-84cfcf8786-jl55l authentication-service] 	/go/src/app/db.go:84 +0x15c
[authentication-service-84cfcf8786-jl55l authentication-service] main.(*server).IsEmailRegistered(0xda1030, 0xa2a0c0, 0xc00010d2c0, 0xc00010d2f0, 0xda1030, 0xc00010d2c0, 0xc000052b30)
[authentication-service-84cfcf8786-jl55l authentication-service] 	/go/src/app/server.go:20 +0x3b
[authentication-service-84cfcf8786-jl55l authentication-service] github.com/acubed-tm/authentication-service/protofiles._AuthService_IsEmailRegistered_Handler(0x920d60, 0xda1030, 0xa2a0c0, 0xc00010d2c0, 0xc000099080, 0x0, 0xa2a0c0, 0xc00010d2c0, 0xc000028860, 0x19)
[authentication-service-84cfcf8786-jl55l authentication-service] 	/go/src/app/protofiles/auth.pb.go:760 +0x217
[authentication-service-84cfcf8786-jl55l authentication-service] google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001980, 0xa2e840, 0xc000074a80, 0xc0000e4800, 0xc00010c480, 0xd386a0, 0x0, 0x0, 0x0)
[authentication-service-84cfcf8786-jl55l authentication-service] 	/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1024 +0x4f4
[authentication-service-84cfcf8786-jl55l authentication-service] google.golang.org/grpc.(*Server).handleStream(0xc000001980, 0xa2e840, 0xc000074a80, 0xc0000e4800, 0x0)
[authentication-service-84cfcf8786-jl55l authentication-service] 	/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1313 +0xd97
[authentication-service-84cfcf8786-jl55l authentication-service] google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00014c100, 0xc000001980, 0xa2e840, 0xc000074a80, 0xc0000e4800)
[authentication-service-84cfcf8786-jl55l authentication-service] 	/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:722 +0xbb
[authentication-service-84cfcf8786-jl55l authentication-service] created by google.golang.org/grpc.(*Server).serveStreams.func1
[authentication-service-84cfcf8786-jl55l authentication-service] 	/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:720 +0xa1
[edge-59db768546-c6rr7 edge] 2020/02/15 12:55:22 Returning error: rpc error: code = Unavailable desc = transport is closing
[edge-59db768546-c6rr7 edge] 2020/02/15 12:55:22 "POST http://10.103.153.221/v1/auth/meet HTTP/1.1" from 192.168.64.1:60374 - 200 98B in 1.046965181s
[authentication-service-84cfcf8786-jl55l authentication-service] 2020/02/15 12:55:27 Starting server
```

**Comment by lennykr** [comment]
Dit lijkt impact te hebben op vrijwel elke route. In uitzonderlijke gevallen werkt een route tijdelijk wel.

**Comment by holly-hacker** [comment]
```
panic: interface conversion: interface {} is nil, not string
main.GetUuidByEmail(0xc000028880, 0x17, 0xc0000f9ac0, 0x40fab3, 0x908b00, 0x920d60)
	/go/src/app/db.go:84 +0x15c
```
Ik ben blijkbaar ergens vergeten te checken voor nil voor ik cast. Ik dacht dat ik dat overal gedaan had.

**Comment by holly-hacker** [comment]
Gebeurt enkel als een account geen UUID heeft, wat nooit mag voorkomen (wss slechte testdata). Ik sluit dit als non-issue.
```go
func GetUuidByEmail(email string) (string, error) {
	query := "MATCH (:Email{emailAddress: {email}})<-[:HAS_EMAIL]-(a:Account) RETURN a.uuid"
	variables := map[string]interface{}{"email": email}
	uuid, err := FetchSingle(query, variables)
	if err != nil {
		return "", err
	}
	return uuid.(string), nil // line 84
}
```

**Comment by lennykr** [comment]
Dat mag wel voorkomen. Gebruikers zonder `uuid` zijn in dit geval mensen die een invite hebben ontvangen op hun e-mailadres maar nog geen account hebben aangemaakt.

**Comment by lennykr** [comment]
@HoLLy-HaCKeR  Kan je hier nog eens naar kijken?
